name: "[CI] Emulator Android"workflow_dispatch:

on:
  push:
    branches: [ main ]

jobs:
  subir-emulador:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar ambiente
        run: |
          echo "y" | sdkmanager "platforms;android-33" "system-images;android-33;google_apis;x86_64"
          echo "no" | avdmanager create avd -n my_avd -k "system-images;android-33;google_apis;x86_64" --force
      - name: Iniciar emulador
        run: |
          emulator -avd my_avd -no-window &
          adb wait-for-device
      - name: Instalar aplicativo
        run: |
          adb install -r app-release.apk
      - name: Executar testes
        run: |
          # Comandos para executar seus testes (ex: ./gradlew test)
      - name: Listar storage
        run: |
          adb shell ls /data/data/com.example.myapp
      - name: Parar emulador
        run: |
          adb emu kill
