name: Android Emulator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Android Emulator
        uses: android-actions/android-emulator-runner@v1
        with:
          api-level: '30'
          arch: 'x86_64'
          force-avd-creation: true

      - name: Start Emulator
        run: |
          emulator -avd test -no-skin -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82

      # Adicione passos para rodar testes aqui
