name: Subir Emulador Android e Listar Storage

on:
  push:
    branches: [ main ]

jobs:
  subir-emulador:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Criar AVD
        run: |
          echo "no" | avdmanager create avd -n my_avd -k "system-images;android-33;google_apis;x86_64" --force
      - name: Iniciar emulador
        run: |
          emulator -avd my_avd -no-window &
          adb wait-for-device
      - name: Instalar aplicativo
        run: |
          adb install -r app-release.apk
      - name: Executar testes
        run: |
          # Comandos para executar seus testes (ex: ./gradlew test)
      - name: Listar storage
        run: |
          adb shell ls /data/data/com.example.myapp
      - name: Parar emulador
        run: |
          adb emu kill
